In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("dataset_for_Naive_Bayes.csv")
print(df);

    Unnamed: 0   Outlook Temperature Humidity  Windy Play Golf
0            0     Rainy         Hot     High  False        No
1            1     Rainy         Hot     High   True        No
2            2  Overcast         Hot     High  False       Yes
3            3     Sunny        Mild     High  False       Yes
4            4     Sunny        Cool   Normal  False       Yes
5            5     Sunny        Cool   Normal   True        No
6            6  Overcast        Cool   Normal   True       Yes
7            7     Rainy        Mild     High  False        No
8            8     Rainy        Cool   Normal  False       Yes
9            9     Sunny        Mild   Normal  False       Yes
10          10     Rainy        Mild   Normal   True       Yes
11          11  Overcast        Mild     High   True       Yes
12          12  Overcast         Hot   Normal  False       Yes
13          13     Sunny        Mild     High   True        No


In [6]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df['Outlook']=le.fit_transform(df['Outlook'])
df['Outlook'].unique()

array([1, 0, 2])

In [8]:
print(df['Outlook'])

0     1
1     1
2     0
3     2
4     2
5     2
6     0
7     1
8     1
9     2
10    1
11    0
12    0
13    2
Name: Outlook, dtype: int64


In [9]:
df['Temperature']=le.fit_transform(df['Temperature'])
df['Temperature'].unique()
print(df['Temperature'])

0     1
1     1
2     1
3     2
4     0
5     0
6     0
7     2
8     0
9     2
10    2
11    2
12    1
13    2
Name: Temperature, dtype: int64


In [10]:
df['Humidity']=le.fit_transform(df['Humidity'])
df['Humidity'].unique()
print(df['Humidity'])

0     0
1     0
2     0
3     0
4     1
5     1
6     1
7     0
8     1
9     1
10    1
11    0
12    1
13    0
Name: Humidity, dtype: int64


In [11]:
df['Play Golf']=le.fit_transform(df['Play Golf'])
df['Play Golf'].unique()
print(df['Play Golf'])

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play Golf, dtype: int64


In [13]:
df['Windy']=le.fit_transform(df['Windy'])
df['Windy'].unique()
print(df['Windy'])

0     0
1     1
2     0
3     0
4     0
5     1
6     1
7     0
8     0
9     0
10    1
11    1
12    0
13    1
Name: Windy, dtype: int64


In [14]:
print(df)

    Unnamed: 0  Outlook  Temperature  Humidity  Windy  Play Golf
0            0        1            1         0      0          0
1            1        1            1         0      1          0
2            2        0            1         0      0          1
3            3        2            2         0      0          1
4            4        2            0         1      0          1
5            5        2            0         1      1          0
6            6        0            0         1      1          1
7            7        1            2         0      0          0
8            8        1            0         1      0          1
9            9        2            2         1      0          1
10          10        1            2         1      1          1
11          11        0            2         0      1          1
12          12        0            1         1      0          1
13          13        2            2         0      1          0


In [15]:
df.to_csv('trans-df.csv')

In [17]:
import numpy as np
df1=np.array(df)
print(df1)

[[ 0  1  1  0  0  0]
 [ 1  1  1  0  1  0]
 [ 2  0  1  0  0  1]
 [ 3  2  2  0  0  1]
 [ 4  2  0  1  0  1]
 [ 5  2  0  1  1  0]
 [ 6  0  0  1  1  1]
 [ 7  1  2  0  0  0]
 [ 8  1  0  1  0  1]
 [ 9  2  2  1  0  1]
 [10  1  2  1  1  1]
 [11  0  2  0  1  1]
 [12  0  1  1  0  1]
 [13  2  2  0  1  0]]


In [22]:
df2=df1[:,1:6]
print(df2)

[[1 1 0 0 0]
 [1 1 0 1 0]
 [0 1 0 0 1]
 [2 2 0 0 1]
 [2 0 1 0 1]
 [2 0 1 1 0]
 [0 0 1 1 1]
 [1 2 0 0 0]
 [1 0 1 0 1]
 [2 2 1 0 1]
 [1 2 1 1 1]
 [0 2 0 1 1]
 [0 1 1 0 1]
 [2 2 0 1 0]]


In [23]:
X=df2[:,0:4]
Y=df2[:,4]

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

In [31]:
print(X_train)

[[1 1 0 1]
 [0 1 1 0]
 [1 1 0 0]
 [2 2 0 1]
 [2 2 1 0]
 [1 0 1 0]
 [0 2 0 1]
 [2 0 1 1]]


In [32]:
print(Y_train)

[0 1 0 0 1 1 1 0]


In [33]:
print(X_test)
print(y_test)

[[2 2 0 0]
 [1 2 0 0]
 [0 0 1 1]
 [0 1 0 0]
 [1 2 1 1]
 [2 0 1 0]]
[1 0 1 1 1 1]


In [34]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

model=GaussianNB()
model.fit(X_train,Y_train)

y_prediction = model.predict(X_test)
print("Predicted class:", y_prediction)
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_prediction)*100)

Predicted class: [0 1 1 1 1 1]
Gaussian Naive Bayes model accuracy(in %): 66.66666666666666


In [45]:
#fro Sunny , Hot , Normal , False
X1=np.array([[2, 1, 1, 0]])

prediction = model.predict(X1)

# 1 => Play Golf = "Yes"
# 0 => Play Golf = "No"
print("Predicted class:", prediction[0])

Predicted class: 1
